### ISSUE TITLE
认证失败，报的异常是jsonObject解析失败，原因是返回的是类似认证失败的文案，分传入的json文案

### ISSUE THREAD

**Issue by mirocolo** [xingePush/xinge-api-java#34]
Exception in thread "main" org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
	at org.json.JSONTokener.syntaxError(JSONTokener.java:451)
	at org.json.JSONObject.<init>(JSONObject.java:195)
	at org.json.JSONObject.<init>(JSONObject.java:319)
	at com.tencent.xinge.XingeApp.callRestful(XingeApp.java:145)
	at com.tencent.xinge.XingeApp.pushApp(XingeApp.java:62)
	at com.loovee.newsale.business.service.impl.PushServiceImpl.main(PushServiceImpl.java:58)

可以考虑返回json或者再包一层

**Comment by sinboun** [comment]
+1
