### ISSUE TITLE
怀疑提供的api没设置timeout导致线程一直被hold住

### ISSUE THREAD

**Issue by Stevenhuangqian** [xingePush/xinge-api-java#38]
最近接入了信鸽推送发现通道莫名会无法发送。工程内所有功能正常，内存、cpu、io都没问题
查看了下堆栈，发现开的所有线程都是卡住：
java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
	- locked <0x00000004ed23d1a0> (a java.lang.Object)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:930)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	- locked <0x00000004ed23d1b0> (a sun.security.ssl.AppInputStream)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	- locked <0x00000004ed2832c8> (a java.io.BufferedInputStream)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:704)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1569)
	- locked <0x00000004ed287338> (a sun.net.www.protocol.https.DelegateHttpsURLConnection)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	- locked <0x00000004ed287338> (a sun.net.www.protocol.https.DelegateHttpsURLConnection)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	- locked <0x00000004ed2872e0> (a sun.net.www.protocol.https.HttpsURLConnectionImpl)
	at com.tencent.xinge.XingeApp.callRestful(XingeApp.java:109)
	at com.tencent.xinge.XingeApp.pushApp(XingeApp.java:60)

看了下源代码。感觉是没设置超时时间，并且信鸽服务器也没主动断开。线程一直hold住？

**Comment by zengweijin** [comment]
z这里具体使用的 sdk  版本是？
