### ISSUE TITLE
大量线程被错误hold住

### ISSUE THREAD

**Issue by Stevenhuangqian** [xingePush/xinge-api-java#42]
"OkHttp ConnectionPool" #200 daemon prio=5 os_prio=0 tid=0x00007f9920150800 nid=0xb73 in Object.wait() [0x00007f98759c3000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:460)
	at okhttp3.ConnectionPool$1.run(ConnectionPool.java:67)
	- locked <0x00000007bcc25540> (a okhttp3.ConnectionPool)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

全部线程都卡在这。可以确定是引入最新版本的信鸽导致(本人项目中原来没使用到okhttp包)

**Comment by zengweijin** [comment]
对应的信鸽sdk  版本能提供到下吗？
